default['license']['key'] = '123456789'
default['data']['wal']['dir'] = '/mnt/influxdb/wal'
default['data']['data']['dir'] = '/mnt/influxdb/data'
default['data']['hh']['dir'] = '/mnt/influxdb/hh'
default['data']['secret'] = 'HIJKLMNOP123'
